{% set name = "arraymap" %}
{% set version = "0.1.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44746407f3f310cafd8c31edbc705f7fc87a42c958cf6164bfd5048deda6b9fb

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/static-frame/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Dictionary-like lookup from NumPy array values to their integer positions.
  dev_url: https://github.com/static-frame/{{ name }}

extra:
  recipe-maintainers:
    - flexatone
    - chaburkland
