{% set name = "arraymap" %}
{% set version = "0.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8409b499fb2cb3fdd253e85c5277828c9215a9692235dad202069f0384ab5f8f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
  run:
    - python

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/static-frame/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Dictionary-like lookup from NumPy array values to their integer positions.
  dev_url: https://github.com/static-frame/{{ name }}

extra:
  recipe-maintainers:
    - flexatone
    - chaburkland
