{% set name = "arraymap" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af1aa15f9f0c799888326561275052b4ea709b0a3a2ff58d01c55a447f8b1213

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/static-frame/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Dictionary-like lookup from NumPy array values to their integer positions.
  dev_url: https://github.com/static-frame/{{ name }}

extra:
  recipe-maintainers:
    - flexatone
    - chaburkland
